#database-type: "FLAT_FILE" #Types: FLAT_FILE, MONGODB

#database:
#  uri: "mongodb://localhost:27017"
#  collection: "basic"

commands:
  discord: "&eDiscord: &dminemen.club/discord"
  store: "&eStore: &dstore.minemen.club"
  website: "&eWebsite: &dminemen.club"
  tiktok: "&eTikTok: &dtiktok.com/@minemen_club"
  twitter: "&eTwitter: &dtwitter.com/Minemen_Network"
  youtube: "&eYouTube: &dyoutube.com/@minemen_club"

join:
  usage: "&e&lUsage: &e/join &d&l<server>"
  joining: "&eJoining &d{server}&e..."
  failed: "&cThere is no online server named &e{server}&c."

global-chat:
  status-changed: "&eGlobal chat is now {status} &efor you."
  format: # {status}
    enabled: "&aenabled"
    disabled: "&cdisabled"
  disabled: "&cYou have the global chat disabled, so you cannot chat either. (/toggleglobalchat)"

chat-filter:
  status-changed: "&eChat filter is now {status} &efor you."
  format: # {status}
    enabled: "&aenabled"
    disabled: "&cdisabled"
  banned-words:
    - fool
    - dumb
    - shit
    - retard
    - fuck
    - kys
    - nigger

settings-menu:
  title: "&e&lSettings"
  size: 27
  items:
    global-chat:
      name: "&e&lGlobal Chat"
      slot: 10
      material: PAPER
      data: 0
      lore:
        - "&7See public messages."
        - " "
        - " "
        - " "
        - " "
        - "&eClick to change!"
      command: "toggleglobalchat"
    private-messages:
      name: "&e&lPrivate Messages"
      slot: 11
      material: BOOK_AND_QUILL
      data: 0
      lore:
        - "&7Let others /message you."
        - " "
        - " "
        - " "
        - " "
        - "&eClick to change!"
      command: "openbook 2523"
    message-sounds:
      name: "&e&lMessage Sounds"
      slot: 12
      material: EGG
      data: 0
      lore:
        - "&7Private message alerts."
        - " "
        - " "
        - " "
        - " "
        - "&eClick to change!"
      command: "openbook 2523"
    profanity-filter:
      name: "&e&lProfanity Filter"
      slot: 13
      material: ROTTEN_FLESH
      data: 0
      lore:
        - "&7Hide rude and toxic words."
        - " "
        - " "
        - " "
        - " "
        - "&eClick to change!"
      command: "togglechatfilter"
  refill-glass:
    enabled: true
    data: 15
    slots:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      #- "10"
      #- "11"
      #- "12"
      #- "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"


changelog-menu:
  title: "&e&lLatest News"
  size: 18
  items:
    update-1:
      name: "&e&lFireball Event"
      slot: 9
      material: BOOK
      data: 0
      lore:
        - "&eTime: &dMar 16, 2024"
        - ""
        - "&eClick to view!"
      command: "openbook 9237"
    update-2:
      name: "&e&lBridges Update"
      slot: 10
      material: BOOK
      data: 0
      lore:
        - "&eTime: &dDec 31, 2023"
        - ""
        - "&eClick to view!"
      command: "openbook 2523"
  refill-glass:
    enabled: true
    data: 15
    slots:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"

#Storage
player-settings:
  ce4edfc7-7058-4266-9dd6-17c8b9f43dbe:
    global-chat: true
    chat-filter: true
